name: AI Blog Automation

on:
  repository_dispatch:
    types: [new_post]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-generativeai gspread requests google-auth

      - name: Write service account JSON to file
        run: echo "${{ secrets.GOOGLE_CREDS_JSON }}" > google-creds.json

      - name: Run automation script
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          BLOGGER_TOKEN: ${{ secrets.BLOGGER_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python main.py "${{ github.event.client_payload.topic }}" "${{ github.event.client_payload.row }}"
